[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 5001
  targetPort = 5173

[[redirects]]
  from = "/api/monday/units"
  to = "/.netlify/functions/monday-units"
  status = 200

[[redirects]]
  from = "/api/monday/missing-subitems/*"
  to = "/.netlify/functions/monday-missing-subitems"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 