[build]
  publish = "client/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Note: This redirect is commented out because you should use VITE_API_URL environment variable instead
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-server.com/api/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 