services:
  - type: web
    name: rental-application-pro
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ENCRYPTION_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true 